name: usdn-test
# Todo force .env.test usage instead of TEST_* variables

services:
  anvil:
    container_name: usdn-anvil-test
    image: 927114455157.dkr.ecr.eu-central-1.amazonaws.com/usdn-backend:smardex-usdn-contracts-0.20.0
    volumes:
      - ./anvil-scripts-custom:/anvil-scripts-custom
      - ./.env.test.fork:/usr/app/.env.fork
    networks:
      - usdn-test-network
    logging:
      options:
        max-size: '20m'
        max-file: '5'
    ports:
      - '${TEST_FORK_PORT:-8546}:${TEST_FORK_PORT:-8545}'
    entrypoint:
      - /bin/sh
      - /anvil-scripts-custom/entrypoint.sh
    environment:
      - FORK_PORT=${TEST_FORK_PORT:-8545}
      - FORK_STORAGE_CACHING=${TEST_FORK_STORAGE_CACHING:-false}
      - FORK_URL=${TEST_FORK_URL:-https://eth-mainnet.g.alchemy.com/v2/ZMTGh2wcbFIUDheXaKBN7cFHBfccH-RT}
      - FORK_CHAIN_ID=${TEST_FORK_CHAIN_ID:-31337}
      - DEPLOY_CONTRACTS=${TEST_DEPLOY_CONTRACTS:-true}
    healthcheck:
      test: ['CMD-SHELL', 'test "$(stat -c%s /usr/app/.env.fork)" -eq 669']
      interval: 5s
      retries: 30
      start_period: 30s

  database:
    container_name: usdn-database-test
    image: postgres:alpine3.19
    hostname: usdn-database-test
    ports:
      - '5433:5432'
    networks:
      - usdn-test-network
    logging:
      options:
        max-size: '10m'
        max-file: '5'
    environment:
      POSTGRES_PASSWORD: '${TEST_DB_PASSWORD:-postgres}'
      POSTGRES_USER: '${TEST_DB_USER:-postgres}'
      POSTGRES_DB: '${TEST_DB_NAME:-postgres-test}'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres} -p 5432']
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

networks:
  usdn-test-network:
    driver: bridge
    name: usdn-test-network
